name: Bench

on: [push]

jobs:
  traanslate:
    name: Bench
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install
      run: |
        sudo apt-get update && apt-get -y install clang-13 make curl procps file git cmake python3 libtinfo-dev libzip-dev ninja-build
        sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang-13 999
        sudo update-alternatives --set cc /usr/bin/clang-13
        sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-13 999
        sudo update-alternatives --set c++ /usr/bin/clang++-13
        sudo ln -sf /usr/bin/clang-13 /usr/bin/clang
        sudo ln -sf /usr/bin/clang++-13 /usr/bin/clang++